// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "operator/pkg/apis/myweb/v1"
	mywebv1 "operator/pkg/clientset/typed/myweb/v1"

	gentype "k8s.io/client-go/gentype"
)

// fakeMyWebs implements MyWebInterface
type fakeMyWebs struct {
	*gentype.FakeClientWithList[*v1.MyWeb, *v1.MyWebList]
	Fake *FakeOperatorV1
}

func newFakeMyWebs(fake *FakeOperatorV1, namespace string) mywebv1.MyWebInterface {
	return &fakeMyWebs{
		gentype.NewFakeClientWithList[*v1.MyWeb, *v1.MyWebList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("mywebs"),
			v1.SchemeGroupVersion.WithKind("MyWeb"),
			func() *v1.MyWeb { return &v1.MyWeb{} },
			func() *v1.MyWebList { return &v1.MyWebList{} },
			func(dst, src *v1.MyWebList) { dst.ListMeta = src.ListMeta },
			func(list *v1.MyWebList) []*v1.MyWeb { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.MyWebList, items []*v1.MyWeb) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
