apiVersion: operator.k8s-summit.org/v1
kind: Web
metadata:
  name: myres1
  namespace: default
spec:
  image: nginx
  nodePortNumber: 30080
  page_html: |
    <html>
      <body>
        <h1>Hello, World!</h1>
      </body>
    </html>
  
