// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "web-crd/pkg/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// MyWebs returns a MyWebInformer.
	MyWebs() MyWebInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// MyWebs returns a MyWebInformer.
func (v *version) MyWebs() MyWebInformer {
	return &myWebInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
