// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	apismywebv1 "operator/pkg/apis/myweb/v1"
	clientset "operator/pkg/clientset"
	internalinterfaces "operator/pkg/informers/externalversions/internalinterfaces"
	mywebv1 "operator/pkg/listers/myweb/v1"
	time "time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MyWebInformer provides access to a shared informer and lister for
// MyWebs.
type MyWebInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() mywebv1.MyWebLister
}

type myWebInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMyWebInformer constructs a new informer for MyWeb type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMyWebInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMyWebInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMyWebInformer constructs a new informer for MyWeb type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMyWebInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OperatorV1().MyWebs(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OperatorV1().MyWebs(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OperatorV1().MyWebs(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OperatorV1().MyWebs(namespace).Watch(ctx, options)
			},
		}, client),
		&apismywebv1.MyWeb{},
		resyncPeriod,
		indexers,
	)
}

func (f *myWebInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMyWebInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *myWebInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apismywebv1.MyWeb{}, f.defaultInformer)
}

func (f *myWebInformer) Lister() mywebv1.MyWebLister {
	return mywebv1.NewMyWebLister(f.Informer().GetIndexer())
}
