apiVersion: operator.k8s-summit.org/v1
kind: MyWeb
metadata:
  name: myweb
  namespace: default
spec:
  image: nginx
  nodePortNumber: 30080
  pageContentHtml: |
    <html>
      <body>
        <h1>Hello, World!</h1>
      </body>
    </html>
  
