// Code generated by lister-gen. DO NOT EDIT.

package v1

// MyWebListerExpansion allows custom methods to be added to
// MyWebLister.
type MyWebListerExpansion interface{}

// MyWebNamespaceListerExpansion allows custom methods to be added to
// MyWebNamespaceLister.
type MyWebNamespaceListerExpansion interface{}
