// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	mywebv1 "web-crd/pkg/apis/myweb/v1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// MyWebLister helps list MyWebs.
// All objects returned here must be treated as read-only.
type MyWebLister interface {
	// List lists all MyWebs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*mywebv1.MyWeb, err error)
	// MyWebs returns an object that can list and get MyWebs.
	MyWebs(namespace string) MyWebNamespaceLister
	MyWebListerExpansion
}

// myWebLister implements the MyWebLister interface.
type myWebLister struct {
	listers.ResourceIndexer[*mywebv1.MyWeb]
}

// NewMyWebLister returns a new MyWebLister.
func NewMyWebLister(indexer cache.Indexer) MyWebLister {
	return &myWebLister{listers.New[*mywebv1.MyWeb](indexer, mywebv1.Resource("myweb"))}
}

// MyWebs returns an object that can list and get MyWebs.
func (s *myWebLister) MyWebs(namespace string) MyWebNamespaceLister {
	return myWebNamespaceLister{listers.NewNamespaced[*mywebv1.MyWeb](s.ResourceIndexer, namespace)}
}

// MyWebNamespaceLister helps list and get MyWebs.
// All objects returned here must be treated as read-only.
type MyWebNamespaceLister interface {
	// List lists all MyWebs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*mywebv1.MyWeb, err error)
	// Get retrieves the MyWeb from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*mywebv1.MyWeb, error)
	MyWebNamespaceListerExpansion
}

// myWebNamespaceLister implements the MyWebNamespaceLister
// interface.
type myWebNamespaceLister struct {
	listers.ResourceIndexer[*mywebv1.MyWeb]
}
