// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"
	mywebv1 "web-crd/pkg/apis/myweb/v1"
	scheme "web-crd/pkg/clientset/scheme"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// MyWebsGetter has a method to return a MyWebInterface.
// A group's client should implement this interface.
type MyWebsGetter interface {
	MyWebs(namespace string) MyWebInterface
}

// MyWebInterface has methods to work with MyWeb resources.
type MyWebInterface interface {
	Create(ctx context.Context, myWeb *mywebv1.MyWeb, opts metav1.CreateOptions) (*mywebv1.MyWeb, error)
	Update(ctx context.Context, myWeb *mywebv1.MyWeb, opts metav1.UpdateOptions) (*mywebv1.MyWeb, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, myWeb *mywebv1.MyWeb, opts metav1.UpdateOptions) (*mywebv1.MyWeb, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*mywebv1.MyWeb, error)
	List(ctx context.Context, opts metav1.ListOptions) (*mywebv1.MyWebList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *mywebv1.MyWeb, err error)
	MyWebExpansion
}

// myWebs implements MyWebInterface
type myWebs struct {
	*gentype.ClientWithList[*mywebv1.MyWeb, *mywebv1.MyWebList]
}

// newMyWebs returns a MyWebs
func newMyWebs(c *OperatorV1Client, namespace string) *myWebs {
	return &myWebs{
		gentype.NewClientWithList[*mywebv1.MyWeb, *mywebv1.MyWebList](
			"mywebs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *mywebv1.MyWeb { return &mywebv1.MyWeb{} },
			func() *mywebv1.MyWebList { return &mywebv1.MyWebList{} },
		),
	}
}
